@startuml

' Styles
hide empty members
hide empty methods
' End Styles


' Functions definition

    

    !function member($type, $name)
        !$stringLength = %strlen($name)
        !$positionPar = %strpos($name, "(")
        !$positionParFermante = %strpos($name, ")")

        !if ($positionPar >= 0 && $positionParFermante - 1 != $positionPar) 
            !$stringArguments = %substr($name, $positionPar + 1, $positionParFermante - $positionPar - 1)

            !$name = %substr($name, 0, $positionPar + 1)

            !$arguments = ""

            !foreach $argument in %splitstr($stringArguments, ", ")
                !if (%strlen($arguments) > 0)
                    !$arguments = $arguments + ", "
                !endif
                !$arguments = $arguments + "<color:green>" + $argument + "</color>"
            !endfor

            !$name = $name + $arguments + ")"
        !endif

        !return $name + " : <color:green>" + $type + "</color>"
    !endfunction

    !function list($type, $name)
    !return member("List<" + $type + ">", $name)
    !endfunction

    !function int($name)
    !return member(int, $name)
    !endfunction

    !function string($name)
    !return member(String, $name)
    !endfunction

    !function void($name)
    !return member(void, $name)
    !endfunction

    !function point($n1, $n2, $sign)
        !return $n1 + $sign + $n2
        
    !endfunction

    !function extends($child, $parent, $dir = false)
    
        !if ($dir == false)
            !$response = point($child, $parent, "--|>")
        !else
            !$response = point($child, $parent, "-" + $dir + "-|>")
        !endif

        !return $response
    !endfunction

' End functions definition

@enduml