@startuml

!include class_diagram_utils.puml
abstract Demo {

}

class DemoInherits {

}

extends(DemoInherits, Demo)

class Athlete {
    -string(nom)
    -float(prenom)
    -table(int, tableDeChiffres, 4)
    -table(int, tableDeChiffres)

    +string("getNom()")
    +string("getNom(List<QuelqueChose> list)")
    +void("setNom(String)")
    +string("getPrenom()")
    +void("setPrenom(String)")
    +member("HashMap<Integer, String>", "getSomething(int, List)")
}

class Course {
    -int(libelle)

    +string("getLibelle()")
    +void("affecterAthlete(Athlete, int)")
    +void("enregistrerTemps(int)")
    +void("start()")
    +void("stop()")
    +float("stop()")
    +member(double, "stop()")
    +member(Athlete, "getConcurrent(int)")
    +member(Athlete, "getVainqueur()")
    +list(Athlete, "getVainqueur()")
}

class Couloir {
    -int(num)

    +int("getNum()")
    +void("setAthlete(Athlete)")
    +member(Athlete, "getAthlete()")
    +int("getTemps()")
    +void("start()")
    +void("stop()")
}

Couloir *-right- Athlete
Course o-- Couloir : couloirs


@enduml