@startuml

!include class_diagram_utils.puml
!include usecase_diagram_utils.puml


rectangle Alala {
    usecase("Commander en ligne", order)
    usecase("Visualiser le prix d'articles", load)
}

actor Client as clt

clt -right- load
clt -right- order
@enduml
